name: finance_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  go_router: ^16.2.1
  flutter_svg: ^2.2.1
  pin_code_fields: ^8.0.1


  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


  fonts:
  - family: Urbanist
    fonts:
    - asset: assets/fonts/Urbanist-Regular.ttf
    - asset: assets/fonts/Urbanist-Medium.ttf
    - asset: assets/fonts/Urbanist-Bold.ttf
